### ISSUE TITLE
Sugerencia: tablero Kanban con las tareas específicas pendientes

### ISSUE THREAD

**Issue by fx-biocoder** [federicoviola/classplanner#2]
Sería ideal contar con un tablero que tenga una lista de tareas a realizar. Me tomé el atrevimiento de crear un tablero de ejemplo en Taiga.io, dejo el link: [click aquí.](https://tree.taiga.io/project/fx-biocoder-classplanner/kanban).

Se podría incluir el link al tablero en el README del repo, para que esté visible a los que deseen contribuir. Se puede gestionar el acceso al tablero solicitando un correo electrónico a los nuevos participantes, y así otorgarles permisos para agregar/tomar tareas.

**Comment by federicoviola** [comment]
> 

Genia!! Como empezamos a editar ahi??

**Comment by fx-biocoder** [comment]
Pasame tu correo electrónico y te agrego a la lista de miembros, de paso te cedo los derechos administrativos sobre el tablero

**Comment by federicoviola** [comment]
> Pasame tu correo electrónico y te agrego a la lista de miembros, de paso te cedo los derechos administrativos sobre el tablero

federicoviola@gmail.com

Agregame con esa direccion. Gracias Facu!!
